{
    "name": "Barcode Stock",
    "version": "18.0.1.0.0",
    "category": "Inventory/Logistics",
    "summary": "Warehouse operations (receipts, deliveries, internal transfers) "
    "for the Barcode suite",
    "author": "Binhex, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/barcode-interface",
    "maintainers": ["szalatyzuzanna"],
    "license": "AGPL-3",
    "depends": [
        "barcode_scanner",
        "barcodes",
        "stock",
        "stock_move_line_qty_picked",
    ],
    "data": [
        "views/stock_location_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "barcode_stock/static/src/scss/picking_filters.scss",
            "barcode_stock/static/src/xml/barcode_stock_templates.xml",
            "barcode_stock/static/src/js/utils/move_progress.esm.js",
            "barcode_stock/static/src/js/utils/avatar.esm.js",
            "barcode_stock/static/src/js/services/barcode_scanner_state.esm.js",
            "barcode_stock/static/src/js/services/barcode_scanner_sync.esm.js",
            "barcode_stock/static/src/js/components/picking_move_card.esm.js",
            "barcode_stock/static/src/js/components/picking_move_list.esm.js",
            "barcode_stock/static/src/js/components/picking_done_card.esm.js",
            "barcode_stock/static/src/js/components/picking_done_list.esm.js",
            "barcode_stock/static/src/js/components/image_viewer.esm.js",
            "barcode_stock/static/src/js/components/picking_info_tab.esm.js",
            "barcode_stock/static/src/js/screens/warehouse_ops.esm.js",
            "barcode_stock/static/src/js/screens/picking_list_screen.esm.js",
            "barcode_stock/static/src/js/screens/picking_screen.esm.js",
            "barcode_stock/static/src/js/screens/move_wizard_screen.esm.js",
            "barcode_stock/static/src/js/screens/internal_transfer_screen.esm.js",
            "barcode_stock/static/src/js/screens/location_selector_screen.esm.js",
            "barcode_stock/static/src/js/screens/product_selector_screen.esm.js",
            "barcode_stock/static/src/js/screens/user_selector_screen.esm.js",
            "barcode_stock/static/src/js/screens/quick_info.esm.js",
            "barcode_stock/static/src/js/handlers/stock_scan_handlers.esm.js",
            "barcode_stock/static/src/js/tiles/stock_menu_tiles.esm.js",
        ],
        "web.assets_unit_tests": [
            "barcode_stock/static/tests/**/*",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
