from . import vcp_platform
from . import vcp_platform_key
from . import vcp_branch
from . import vcp_rule
from . import vcp_rule_information
from . import vcp_rule_information_mixin
from . import vcp_repository
from . import vcp_repository_branch
from . import vcp_request
from . import vcp_request_label
from . import vcp_review
from . import vcp_comment
from . import res_partner
from . import vcp_host
from . import vcp_host_type
from . import vcp_user
from . import vcp_organization
