from . import account_payment_line
from . import account_payment
from . import account_payment_lot
from . import account_payment_order
from . import account_payment_method_line
from . import account_pain_regulatory_reporting
from . import res_company
from . import res_currency
from . import account_payment_method
from . import res_partner
from . import res_partner_bank
