{
    "name": "Shopify Connector",
    "summary": "GraphQL-first Shopify commerce synchronization",
    "version": "19.0.1.0.0",
    "category": "Sales/Sales",
    "author": "Sawir Studio, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/connector-shopify",
    "license": "AGPL-3",
    "depends": [
        "sale_management",
        "sale_stock",
        "stock",
        "delivery",
        "stock_delivery",
        "account",
        "queue_job",
        "website_sale",
    ],
    "data": [
        "security/shopify_security.xml",
        "security/ir.model.access.csv",
        "data/queue_job.xml",
        "data/ir_cron.xml",
        "views/shopify_instance_views.xml",
        "views/shopify_webhook_event_views.xml",
        "views/shopify_log_views.xml",
        "views/shopify_product_views.xml",
        "views/shopify_collection_views.xml",
        "views/shopify_inventory_views.xml",
        "views/shopify_customer_views.xml",
        "views/shopify_order_views.xml",
        "views/shopify_fulfillment_views.xml",
        "views/shopify_dashboard_views.xml",
        "views/shopify_onboarding_views.xml",
        "views/shopify_operability_views.xml",
        "views/shopify_menus.xml",
    ],
    "external_dependencies": {"python": ["requests"]},
    "installable": True,
    "application": True,
}
